### ISSUE TITLE
Incompleted algorithm and missing checksum value

### ISSUE THREAD

**Issue by bensoy** [rizasabuncu/wpspin#1]
You can get only first 7 digits of wps pin without adding last checksum digit but just transforming hexadecimal mac address to its decimal equivalent. Since a valid pin is 8 digits long, calculation for last digit is required. However, if hexadecimal to decimal conversion results with 8 digit value I have no idea how you can decide which result you will prefer.

Here you can see calculation algorithm that I extracted from some kind of wpspin generator app and rewroted it in php so you can add it to your script

```php
$pin = hexdec($mac);
$chksm = $pin;

for($i=0; ;)
{
	if ($chksm == 0)
	{	
		$chksm = (10 - $i % 10) % 10;
		break;
	}

	$j = $i + 3 * ($chksm % 10);
	$k = $chksm / 10;
	$i = $j + $k % 10;
	$chksm = $k / 10;
}
$pin = $pin.$chksm;
return $pin;
```

**Comment by rizasabuncu** [comment]
Updated, ty :)
